---
title: "23. Python Exception Handling"
desc: "Python Exception Handling"
slug: home
headerImg: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/tutorial/python.png"
date: "November 23, 2022"
infoP: "Python Exception Handling"
spanH2: "Core Concepts"
bottomP: "An event that arises during the operation of an application that obstructs the regular execution of the program's commands is an exception. Python utilizes the try and except block to capture and manage exceptions."
imgC: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/tutorial/amritansh.png"
PH: "Amritansh"
pD: "November 23, 2022"
tag: "Python"
tagDes: "15 Tutorials & Projects"
topic: {
  title: "Python",
tagDes: "15 Tutorials & Projects",
img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/tutorial/arrow.png"

}
author: "Admin"
position: "Editor"
readTime: "20-25 mins"
h1: "Python Exception Handling : "
id: "python-exception-handling"
tableData:
  [
  1. Overview,
  2. Scope of the tutorial,  
  3. What does a Python exception mean?,  
  4. Handling an exception,  
  5. The try and except,
  6. The try except and else,
  7. The try except else and finally,
  8. The try-finally clause,
  9. How to get a proper error message,
  10. Nested try and except,
  11. With a try statement we may have several except statements.,
  12. The Exception of an argument,
  13. Raising an Exception,
  14. User-defined Exceptions,
  15. Summary,
  ]
---

# **Chapter 9**


# **Python Exception Handling (Try…Except…Else…Finally)**


<img src="https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/tutorial/python/Python+Exception+Handling+(Try%E2%80%A6Except%E2%80%A6Else%E2%80%A6Finally).jpg"></img>



## 1. Overview

Python typically stops and produces an error message when an error, or exception as we refer to it, arises. Preventing probable failures and limited stops is exception handling's main objective. Python errors can either be syntax errors in expressions or Python exceptions.


## 2. Scope of the tutorial

This tutorial covers



* Exception in Python
* Handling an exception
* User-defined Exceptions


## 3. What does a Python exception mean?

An exception is a condition that interferes with the program's usual flow of instructions while it is being run. In cases when Python is unable to manage the scripts, an exception is often triggered. Python's representation of an error is an object. The python script has to handle exceptions as soon as they are encountered. Otherwise, it will end and stop on its own.

Syntax


```
Try: 
# Code block 
Try:  These are the statements that may include errors.

except
# This block seems to be optional
# This block will take care of any exceptions that the try block encounters.

else: 
# The Python interpreter will run this code block if no exception is present.

finally:
# The Python interpreter will always run this code.
```



## 4. Handling an exception

Users can raise an exception if there are any doubts about the code, while you can also protect the program by keeping the doubtful code in a **try:** block. Following the **try:** block with an **except** clause would therefore be the most elegant way to resolve the problem.

Let's look at two situations: one where there is no issue and the other where an exception is being raised.


```
Example
m=int(input("Provide a number- "))
n=int(input("Provide a number- "))
print(m/n)
print(m)
print(n)
m+n
m-n
m*n

Output
Provide a number- 20
Provide a number- 0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-8-b7a0239bb262> in <module>
      1 m=int(input("Provide a number- "))
      2 n=int(input("Provide a number- "))
----> 3 print(m/n)
      4 print(m)
      5 print(n)

ZeroDivisionError: division by zero
```



## 5. The try and except


```
Syntax
try:
     # some code
except:
     # Alternate code
```



```
Example
m=int(input("Provide a number- "))
n=int(input("Provide a number- "))

try:
    print(m/n)
except:
    print("Division by zero is not possible")

print(m+n)
print(m*n)

Output
Provide a number- 20
Provide a number- 0
Division by zero is not possible
20
0
```



```
Example2
try:
    m=int(input("Provide a number- "))
    n=int(input("Provide a number- "))
    print(m/n)
except:
    print("Division by zero is not possible")

print(m+n)
print(m*n)

Output
Provide a number- a
Division by zero is not possible
15
50
```



## 6. The try except and else



* If no exception is generated in the try block, then the else block is performed.
* The except block is performed if the exception is raised.

```
Example
m=int(input("Provide a number- "))
n=int(input("Provide a number- "))

try:
    o=m/n
except:
    print("Division by zero is not possible")
else:
    print(o)

print(m+n)
print(m*n)

Output
Provide a number- 20
Provide a number- 0
Division by zero is not possible
20
0
```




## 7. The try except else and finally

finally- In this block the code is always executed


```
Example
m=int(input("Provide a number- "))
n=int(input("Provide a number- "))

try:
    o=m/n
except:
    print("Some error")
else:
    print(o)
finally:
    print(m+n)
    print(m*n)

Output
Provide a number- 20
Provide a number- 0
Some error
20
0
```



## 8. The try-finally clause

Whether a **try:** block exception is triggered or not, but any code that must run is always contained in a **finally:** block.

**Please Note:** You may either include an except clause or a **finally:** clause; neither is possible. However, you cannot use both the **finally:** clause and the else condition together.


```
try:
    cd = open("testfile","w")
try:
    cd = cd.write("Welcome to Learnbay Data science")
finally:
    print("Python Course")
except IOError:
    print("Error: not able to find the file in the location")
```


When an exception is passed in the **try:** block, the **finally:** block gets immediate execution. The except statement, which is present in the higher layer of the try-except statement, is used to handle the exception that is raised after the **finally:** block statements have been fully executed.


## 9. How to get a proper error message


```
try:
    m=int(input("Provide a number- "))
    n=int(input("Provide a number- "))
    print(m/n)
except Exception as o:
    print(o)
finally:
    print("Finally, here is the block")

Output
Provide a number- 20
Provide a number- 0
division by zero
Finally, here is the block
```



## 10. Nested try and except


```
Syntax
try:
    # some code
    try:
        # some code
    except:
        # some code
except:
    # some code
```



```
Example
m=eval(input("Provide a value- "))
try:
    n=int(input("Provide a value- "))
    print(xyz)
    try:
        m/n
    except:
        print("Inner except block")
except:
    print("External except block")

Output
Provide a value- 10
Provide a value- 2
External except block
```



## 11. With a try statement we may have several except statements.


```
Example
try:
    m=int(input("Provide a number- "))
    n=int(input("Provide a number- "))
    print(m/n)
    print(abc)

except ZeroDivisionError:
    print("Division by zero is not possible")
except ValueError:
    print("Invalid value")
except Exception as e:
    print(e)
Output
Provide a number- 20
Provide a number- 5
4.0
name 'abc' is not defined
```



## 12. The Exception of an argument

An exception may be used as an argument in the value that adds further details about the problem. The argument's contents may change depending on the exception. By inserting a variable inside the exception clause, you could maintain track of the exception's argument. You may add a variable after the name of the exception in the unless statement if you just need to write the code to handle one exception.

Example


```
# Defining a function.
def temp_convert(variable):
    try:
         return int(variable)
    except ValueError, Argument:
        print("Argument doesn't include any numerical values\n, Argument")

# Use this function to call the one mentioned above..
temp_convert("abh");

Argument doesn't include any numerical values
invalid literal for int() with base 10: 'abh'
```



## 13. Raising an Exception

You may raise exceptions in a number of ways with the use of a raise statement. Any type of string can be an exception. The increase statement is often shown as


```
try:
    m = int(input("Provide a positive value: "))
    if m <= 0:
        raise ValueError("That value is not a positive!")
    except ValueError as ve:
        print(ve)
    
Output
Provide a positive value: -2
That value is not a positive!
```



## 14. User-defined Exceptions

In Python, you are free to create your own built-in exceptions by obtaining the appropriate classes.

The try: block raises the user-defined exception, which is ultimately managed by the except block. The variable "e" is utilized to construct a Networkerror class instance.


```
Example
try:
    amt=int(input("Specify the amount you wish to send- "))
    try:
        if amt>50000:
            raise
    except:
        print("The amount exceeds the limit or amount is zero or less than zero")
    else:
        print("Amount Transferred")
except Exception as e:
    print(e)
finally:
    print("Thanks for using the app")

Output
Specify the amount you wish to send- 0
The amount exceeds the limit or amount is zero or less than zero
Thanks for using the app
```



```
Example 2
def  gen():
    yield 10
    yield 20
    
g=gen()

for i in range(6):
    try:
        print(next(g))
    except:
        print("stop iteration")
        break

Output
10
20
stop iteration
```



## 15. Summary

Without this technique, exceptions would prevent a program from functioning normally. The method of addressing exception handling deals with situations that prevent a system or program from crashing.
